//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TextileMangementSystemModel", "FK_Order_Buyer", "Buyer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextileManagementSystem.Models.Buyer), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextileManagementSystem.Models.Order), true)]
[assembly: EdmRelationshipAttribute("TextileMangementSystemModel", "FK_Demand_Merchandiser", "Merchandiser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextileManagementSystem.Models.Merchandiser), "Demand", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextileManagementSystem.Models.Demand), true)]
[assembly: EdmRelationshipAttribute("TextileMangementSystemModel", "FK_Demand_Order", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextileManagementSystem.Models.Order), "Demand", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextileManagementSystem.Models.Demand), true)]
[assembly: EdmRelationshipAttribute("TextileMangementSystemModel", "FK_Dying_Demand", "Demand", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextileManagementSystem.Models.Demand), "Dying", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TextileManagementSystem.Models.Dying), true)]
[assembly: EdmRelationshipAttribute("TextileMangementSystemModel", "FK_Knitting_Demand", "Demand", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextileManagementSystem.Models.Demand), "Knitting", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TextileManagementSystem.Models.Knitting), true)]
[assembly: EdmRelationshipAttribute("TextileMangementSystemModel", "FK_Yarn_Demand", "Demand", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextileManagementSystem.Models.Demand), "Yarn", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TextileManagementSystem.Models.Yarn), true)]
[assembly: EdmRelationshipAttribute("TextileMangementSystemModel", "FK_Meeting_Order", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextileManagementSystem.Models.Order), "Meeting", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TextileManagementSystem.Models.Meeting), true)]

#endregion

namespace TextileManagementSystem.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MangementEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MangementEntities object using the connection string found in the 'MangementEntities' section of the application configuration file.
        /// </summary>
        public MangementEntities() : base("name=MangementEntities", "MangementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MangementEntities object.
        /// </summary>
        public MangementEntities(string connectionString) : base(connectionString, "MangementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MangementEntities object.
        /// </summary>
        public MangementEntities(EntityConnection connection) : base(connection, "MangementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Buyer> Buyers
        {
            get
            {
                if ((_Buyers == null))
                {
                    _Buyers = base.CreateObjectSet<Buyer>("Buyers");
                }
                return _Buyers;
            }
        }
        private ObjectSet<Buyer> _Buyers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Demand> Demands
        {
            get
            {
                if ((_Demands == null))
                {
                    _Demands = base.CreateObjectSet<Demand>("Demands");
                }
                return _Demands;
            }
        }
        private ObjectSet<Demand> _Demands;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dying> Dyings
        {
            get
            {
                if ((_Dyings == null))
                {
                    _Dyings = base.CreateObjectSet<Dying>("Dyings");
                }
                return _Dyings;
            }
        }
        private ObjectSet<Dying> _Dyings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Knitting> Knittings
        {
            get
            {
                if ((_Knittings == null))
                {
                    _Knittings = base.CreateObjectSet<Knitting>("Knittings");
                }
                return _Knittings;
            }
        }
        private ObjectSet<Knitting> _Knittings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Meeting> Meetings
        {
            get
            {
                if ((_Meetings == null))
                {
                    _Meetings = base.CreateObjectSet<Meeting>("Meetings");
                }
                return _Meetings;
            }
        }
        private ObjectSet<Meeting> _Meetings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Merchandiser> Merchandisers
        {
            get
            {
                if ((_Merchandisers == null))
                {
                    _Merchandisers = base.CreateObjectSet<Merchandiser>("Merchandisers");
                }
                return _Merchandisers;
            }
        }
        private ObjectSet<Merchandiser> _Merchandisers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Yarn> Yarns
        {
            get
            {
                if ((_Yarns == null))
                {
                    _Yarns = base.CreateObjectSet<Yarn>("Yarns");
                }
                return _Yarns;
            }
        }
        private ObjectSet<Yarn> _Yarns;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Buyers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuyers(Buyer buyer)
        {
            base.AddObject("Buyers", buyer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Demands EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDemands(Demand demand)
        {
            base.AddObject("Demands", demand);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dyings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDyings(Dying dying)
        {
            base.AddObject("Dyings", dying);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Knittings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKnittings(Knitting knitting)
        {
            base.AddObject("Knittings", knitting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Meetings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeetings(Meeting meeting)
        {
            base.AddObject("Meetings", meeting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Merchandisers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMerchandisers(Merchandiser merchandiser)
        {
            base.AddObject("Merchandisers", merchandiser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Yarns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToYarns(Yarn yarn)
        {
            base.AddObject("Yarns", yarn);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextileMangementSystemModel", Name="Buyer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Buyer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Buyer object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="pass">Initial value of the Pass property.</param>
        /// <param name="comName">Initial value of the ComName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        /// <param name="valid">Initial value of the Valid property.</param>
        public static Buyer CreateBuyer(global::System.Int32 id, global::System.String name, global::System.String pass, global::System.String comName, global::System.String email, global::System.String country, global::System.Int32 valid)
        {
            Buyer buyer = new Buyer();
            buyer.ID = id;
            buyer.Name = name;
            buyer.Pass = pass;
            buyer.ComName = comName;
            buyer.Email = email;
            buyer.Country = country;
            buyer.Valid = valid;
            return buyer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private global::System.String _Pass;
        partial void OnPassChanging(global::System.String value);
        partial void OnPassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ComName
        {
            get
            {
                return _ComName;
            }
            set
            {
                OnComNameChanging(value);
                ReportPropertyChanging("ComName");
                _ComName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ComName");
                OnComNameChanged();
            }
        }
        private global::System.String _ComName;
        partial void OnComNameChanging(global::System.String value);
        partial void OnComNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valid
        {
            get
            {
                return _Valid;
            }
            set
            {
                OnValidChanging(value);
                ReportPropertyChanging("Valid");
                _Valid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valid");
                OnValidChanged();
            }
        }
        private global::System.Int32 _Valid;
        partial void OnValidChanging(global::System.Int32 value);
        partial void OnValidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Order_Buyer", "Order")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("TextileMangementSystemModel.FK_Order_Buyer", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("TextileMangementSystemModel.FK_Order_Buyer", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextileMangementSystemModel", Name="Demand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Demand : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Demand object.
        /// </summary>
        /// <param name="no">Initial value of the No property.</param>
        /// <param name="thickness">Initial value of the Thickness property.</param>
        /// <param name="color">Initial value of the Color property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="size">Initial value of the Size property.</param>
        /// <param name="orderNo">Initial value of the OrderNo property.</param>
        /// <param name="merchID">Initial value of the MerchID property.</param>
        public static Demand CreateDemand(global::System.Int32 no, global::System.Double thickness, global::System.String color, global::System.DateTime date, global::System.Double quantity, global::System.Double size, global::System.Int32 orderNo, global::System.Int32 merchID)
        {
            Demand demand = new Demand();
            demand.No = no;
            demand.Thickness = thickness;
            demand.Color = color;
            demand.Date = date;
            demand.Quantity = quantity;
            demand.Size = size;
            demand.OrderNo = orderNo;
            demand.MerchID = merchID;
            return demand;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 No
        {
            get
            {
                return _No;
            }
            set
            {
                if (_No != value)
                {
                    OnNoChanging(value);
                    ReportPropertyChanging("No");
                    _No = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("No");
                    OnNoChanged();
                }
            }
        }
        private global::System.Int32 _No;
        partial void OnNoChanging(global::System.Int32 value);
        partial void OnNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Thickness
        {
            get
            {
                return _Thickness;
            }
            set
            {
                OnThicknessChanging(value);
                ReportPropertyChanging("Thickness");
                _Thickness = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Thickness");
                OnThicknessChanged();
            }
        }
        private global::System.Double _Thickness;
        partial void OnThicknessChanging(global::System.Double value);
        partial void OnThicknessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Double _Quantity;
        partial void OnQuantityChanging(global::System.Double value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.Double _Size;
        partial void OnSizeChanging(global::System.Double value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderNo
        {
            get
            {
                return _OrderNo;
            }
            set
            {
                OnOrderNoChanging(value);
                ReportPropertyChanging("OrderNo");
                _OrderNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderNo");
                OnOrderNoChanged();
            }
        }
        private global::System.Int32 _OrderNo;
        partial void OnOrderNoChanging(global::System.Int32 value);
        partial void OnOrderNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MerchID
        {
            get
            {
                return _MerchID;
            }
            set
            {
                OnMerchIDChanging(value);
                ReportPropertyChanging("MerchID");
                _MerchID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MerchID");
                OnMerchIDChanged();
            }
        }
        private global::System.Int32 _MerchID;
        partial void OnMerchIDChanging(global::System.Int32 value);
        partial void OnMerchIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Demand_Merchandiser", "Merchandiser")]
        public Merchandiser Merchandiser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandiser>("TextileMangementSystemModel.FK_Demand_Merchandiser", "Merchandiser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandiser>("TextileMangementSystemModel.FK_Demand_Merchandiser", "Merchandiser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Merchandiser> MerchandiserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandiser>("TextileMangementSystemModel.FK_Demand_Merchandiser", "Merchandiser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Merchandiser>("TextileMangementSystemModel.FK_Demand_Merchandiser", "Merchandiser", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Demand_Order", "Order")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TextileMangementSystemModel.FK_Demand_Order", "Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TextileMangementSystemModel.FK_Demand_Order", "Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TextileMangementSystemModel.FK_Demand_Order", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("TextileMangementSystemModel.FK_Demand_Order", "Order", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Dying_Demand", "Dying")]
        public Dying Dying
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dying>("TextileMangementSystemModel.FK_Dying_Demand", "Dying").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dying>("TextileMangementSystemModel.FK_Dying_Demand", "Dying").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dying> DyingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dying>("TextileMangementSystemModel.FK_Dying_Demand", "Dying");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dying>("TextileMangementSystemModel.FK_Dying_Demand", "Dying", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Knitting_Demand", "Knitting")]
        public Knitting Knitting
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Knitting>("TextileMangementSystemModel.FK_Knitting_Demand", "Knitting").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Knitting>("TextileMangementSystemModel.FK_Knitting_Demand", "Knitting").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Knitting> KnittingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Knitting>("TextileMangementSystemModel.FK_Knitting_Demand", "Knitting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Knitting>("TextileMangementSystemModel.FK_Knitting_Demand", "Knitting", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Yarn_Demand", "Yarn")]
        public Yarn Yarn
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Yarn>("TextileMangementSystemModel.FK_Yarn_Demand", "Yarn").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Yarn>("TextileMangementSystemModel.FK_Yarn_Demand", "Yarn").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Yarn> YarnReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Yarn>("TextileMangementSystemModel.FK_Yarn_Demand", "Yarn");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Yarn>("TextileMangementSystemModel.FK_Yarn_Demand", "Yarn", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextileMangementSystemModel", Name="Dying")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dying : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dying object.
        /// </summary>
        /// <param name="demandNo">Initial value of the DemandNo property.</param>
        /// <param name="cMC_Decision">Initial value of the CMC_Decision property.</param>
        /// <param name="cMC_DE">Initial value of the CMC_DE property.</param>
        /// <param name="dL">Initial value of the DL property.</param>
        /// <param name="dA">Initial value of the DA property.</param>
        /// <param name="dB">Initial value of the DB property.</param>
        /// <param name="dC">Initial value of the DC property.</param>
        /// <param name="dH">Initial value of the DH property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Dying CreateDying(global::System.Int32 demandNo, global::System.String cMC_Decision, global::System.Double cMC_DE, global::System.Double dL, global::System.Double dA, global::System.Double dB, global::System.Double dC, global::System.Double dH, global::System.DateTime date)
        {
            Dying dying = new Dying();
            dying.DemandNo = demandNo;
            dying.CMC_Decision = cMC_Decision;
            dying.CMC_DE = cMC_DE;
            dying.DL = dL;
            dying.DA = dA;
            dying.DB = dB;
            dying.DC = dC;
            dying.DH = dH;
            dying.Date = date;
            return dying;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DemandNo
        {
            get
            {
                return _DemandNo;
            }
            set
            {
                if (_DemandNo != value)
                {
                    OnDemandNoChanging(value);
                    ReportPropertyChanging("DemandNo");
                    _DemandNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DemandNo");
                    OnDemandNoChanged();
                }
            }
        }
        private global::System.Int32 _DemandNo;
        partial void OnDemandNoChanging(global::System.Int32 value);
        partial void OnDemandNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CMC_Decision
        {
            get
            {
                return _CMC_Decision;
            }
            set
            {
                OnCMC_DecisionChanging(value);
                ReportPropertyChanging("CMC_Decision");
                _CMC_Decision = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CMC_Decision");
                OnCMC_DecisionChanged();
            }
        }
        private global::System.String _CMC_Decision;
        partial void OnCMC_DecisionChanging(global::System.String value);
        partial void OnCMC_DecisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CMC_DE
        {
            get
            {
                return _CMC_DE;
            }
            set
            {
                OnCMC_DEChanging(value);
                ReportPropertyChanging("CMC_DE");
                _CMC_DE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMC_DE");
                OnCMC_DEChanged();
            }
        }
        private global::System.Double _CMC_DE;
        partial void OnCMC_DEChanging(global::System.Double value);
        partial void OnCMC_DEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DL
        {
            get
            {
                return _DL;
            }
            set
            {
                OnDLChanging(value);
                ReportPropertyChanging("DL");
                _DL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DL");
                OnDLChanged();
            }
        }
        private global::System.Double _DL;
        partial void OnDLChanging(global::System.Double value);
        partial void OnDLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DA
        {
            get
            {
                return _DA;
            }
            set
            {
                OnDAChanging(value);
                ReportPropertyChanging("DA");
                _DA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DA");
                OnDAChanged();
            }
        }
        private global::System.Double _DA;
        partial void OnDAChanging(global::System.Double value);
        partial void OnDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DB
        {
            get
            {
                return _DB;
            }
            set
            {
                OnDBChanging(value);
                ReportPropertyChanging("DB");
                _DB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DB");
                OnDBChanged();
            }
        }
        private global::System.Double _DB;
        partial void OnDBChanging(global::System.Double value);
        partial void OnDBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DC
        {
            get
            {
                return _DC;
            }
            set
            {
                OnDCChanging(value);
                ReportPropertyChanging("DC");
                _DC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DC");
                OnDCChanged();
            }
        }
        private global::System.Double _DC;
        partial void OnDCChanging(global::System.Double value);
        partial void OnDCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DH
        {
            get
            {
                return _DH;
            }
            set
            {
                OnDHChanging(value);
                ReportPropertyChanging("DH");
                _DH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DH");
                OnDHChanged();
            }
        }
        private global::System.Double _DH;
        partial void OnDHChanging(global::System.Double value);
        partial void OnDHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Dying_Demand", "Demand")]
        public Demand Demand
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Demand>("TextileMangementSystemModel.FK_Dying_Demand", "Demand").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Demand>("TextileMangementSystemModel.FK_Dying_Demand", "Demand").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Demand> DemandReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Demand>("TextileMangementSystemModel.FK_Dying_Demand", "Demand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Demand>("TextileMangementSystemModel.FK_Dying_Demand", "Demand", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextileMangementSystemModel", Name="Knitting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Knitting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Knitting object.
        /// </summary>
        /// <param name="demandNo">Initial value of the DemandNo property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="color">Initial value of the Color property.</param>
        /// <param name="shade">Initial value of the Shade property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="hole">Initial value of the Hole property.</param>
        /// <param name="totalPoitn">Initial value of the TotalPoitn property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Knitting CreateKnitting(global::System.Int32 demandNo, global::System.Double quantity, global::System.String color, global::System.Double shade, global::System.Double width, global::System.String type, global::System.Int32 hole, global::System.Double totalPoitn, global::System.DateTime date)
        {
            Knitting knitting = new Knitting();
            knitting.DemandNo = demandNo;
            knitting.Quantity = quantity;
            knitting.Color = color;
            knitting.Shade = shade;
            knitting.Width = width;
            knitting.Type = type;
            knitting.Hole = hole;
            knitting.TotalPoitn = totalPoitn;
            knitting.Date = date;
            return knitting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DemandNo
        {
            get
            {
                return _DemandNo;
            }
            set
            {
                if (_DemandNo != value)
                {
                    OnDemandNoChanging(value);
                    ReportPropertyChanging("DemandNo");
                    _DemandNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DemandNo");
                    OnDemandNoChanged();
                }
            }
        }
        private global::System.Int32 _DemandNo;
        partial void OnDemandNoChanging(global::System.Int32 value);
        partial void OnDemandNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Double _Quantity;
        partial void OnQuantityChanging(global::System.Double value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Shade
        {
            get
            {
                return _Shade;
            }
            set
            {
                OnShadeChanging(value);
                ReportPropertyChanging("Shade");
                _Shade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Shade");
                OnShadeChanged();
            }
        }
        private global::System.Double _Shade;
        partial void OnShadeChanging(global::System.Double value);
        partial void OnShadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Double _Width;
        partial void OnWidthChanging(global::System.Double value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hole
        {
            get
            {
                return _Hole;
            }
            set
            {
                OnHoleChanging(value);
                ReportPropertyChanging("Hole");
                _Hole = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hole");
                OnHoleChanged();
            }
        }
        private global::System.Int32 _Hole;
        partial void OnHoleChanging(global::System.Int32 value);
        partial void OnHoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double TotalPoitn
        {
            get
            {
                return _TotalPoitn;
            }
            set
            {
                OnTotalPoitnChanging(value);
                ReportPropertyChanging("TotalPoitn");
                _TotalPoitn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPoitn");
                OnTotalPoitnChanged();
            }
        }
        private global::System.Double _TotalPoitn;
        partial void OnTotalPoitnChanging(global::System.Double value);
        partial void OnTotalPoitnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Knitting_Demand", "Demand")]
        public Demand Demand
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Demand>("TextileMangementSystemModel.FK_Knitting_Demand", "Demand").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Demand>("TextileMangementSystemModel.FK_Knitting_Demand", "Demand").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Demand> DemandReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Demand>("TextileMangementSystemModel.FK_Knitting_Demand", "Demand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Demand>("TextileMangementSystemModel.FK_Knitting_Demand", "Demand", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextileMangementSystemModel", Name="Meeting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Meeting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Meeting object.
        /// </summary>
        /// <param name="orderNo">Initial value of the OrderNo property.</param>
        /// <param name="contact">Initial value of the Contact property.</param>
        /// <param name="details">Initial value of the Details property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Meeting CreateMeeting(global::System.Int32 orderNo, global::System.Int32 contact, global::System.String details, global::System.DateTime date)
        {
            Meeting meeting = new Meeting();
            meeting.OrderNo = orderNo;
            meeting.Contact = contact;
            meeting.Details = details;
            meeting.Date = date;
            return meeting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderNo
        {
            get
            {
                return _OrderNo;
            }
            set
            {
                if (_OrderNo != value)
                {
                    OnOrderNoChanging(value);
                    ReportPropertyChanging("OrderNo");
                    _OrderNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderNo");
                    OnOrderNoChanged();
                }
            }
        }
        private global::System.Int32 _OrderNo;
        partial void OnOrderNoChanging(global::System.Int32 value);
        partial void OnOrderNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private global::System.Int32 _Contact;
        partial void OnContactChanging(global::System.Int32 value);
        partial void OnContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Details
        {
            get
            {
                return _Details;
            }
            set
            {
                OnDetailsChanging(value);
                ReportPropertyChanging("Details");
                _Details = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Details");
                OnDetailsChanged();
            }
        }
        private global::System.String _Details;
        partial void OnDetailsChanging(global::System.String value);
        partial void OnDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Meeting_Order", "Order")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TextileMangementSystemModel.FK_Meeting_Order", "Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TextileMangementSystemModel.FK_Meeting_Order", "Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("TextileMangementSystemModel.FK_Meeting_Order", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("TextileMangementSystemModel.FK_Meeting_Order", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextileMangementSystemModel", Name="Merchandiser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Merchandiser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Merchandiser object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="pass">Initial value of the Pass property.</param>
        public static Merchandiser CreateMerchandiser(global::System.Int32 id, global::System.String name, global::System.String pass)
        {
            Merchandiser merchandiser = new Merchandiser();
            merchandiser.ID = id;
            merchandiser.Name = name;
            merchandiser.Pass = pass;
            return merchandiser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private global::System.String _Pass;
        partial void OnPassChanging(global::System.String value);
        partial void OnPassChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Demand_Merchandiser", "Demand")]
        public EntityCollection<Demand> Demands
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Demand>("TextileMangementSystemModel.FK_Demand_Merchandiser", "Demand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Demand>("TextileMangementSystemModel.FK_Demand_Merchandiser", "Demand", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextileMangementSystemModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="no">Initial value of the No property.</param>
        /// <param name="color">Initial value of the Color property.</param>
        /// <param name="size">Initial value of the Size property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="dia">Initial value of the Dia property.</param>
        /// <param name="shade">Initial value of the Shade property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="buyerID">Initial value of the BuyerID property.</param>
        public static Order CreateOrder(global::System.Int32 no, global::System.String color, global::System.Double size, global::System.Double amount, global::System.Double dia, global::System.Double shade, global::System.DateTime date, global::System.Int32 buyerID)
        {
            Order order = new Order();
            order.No = no;
            order.Color = color;
            order.Size = size;
            order.Amount = amount;
            order.Dia = dia;
            order.Shade = shade;
            order.Date = date;
            order.BuyerID = buyerID;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 No
        {
            get
            {
                return _No;
            }
            set
            {
                if (_No != value)
                {
                    OnNoChanging(value);
                    ReportPropertyChanging("No");
                    _No = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("No");
                    OnNoChanged();
                }
            }
        }
        private global::System.Int32 _No;
        partial void OnNoChanging(global::System.Int32 value);
        partial void OnNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.Double _Size;
        partial void OnSizeChanging(global::System.Double value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Double _Amount;
        partial void OnAmountChanging(global::System.Double value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Dia
        {
            get
            {
                return _Dia;
            }
            set
            {
                OnDiaChanging(value);
                ReportPropertyChanging("Dia");
                _Dia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dia");
                OnDiaChanged();
            }
        }
        private global::System.Double _Dia;
        partial void OnDiaChanging(global::System.Double value);
        partial void OnDiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Shade
        {
            get
            {
                return _Shade;
            }
            set
            {
                OnShadeChanging(value);
                ReportPropertyChanging("Shade");
                _Shade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Shade");
                OnShadeChanged();
            }
        }
        private global::System.Double _Shade;
        partial void OnShadeChanging(global::System.Double value);
        partial void OnShadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuyerID
        {
            get
            {
                return _BuyerID;
            }
            set
            {
                OnBuyerIDChanging(value);
                ReportPropertyChanging("BuyerID");
                _BuyerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuyerID");
                OnBuyerIDChanged();
            }
        }
        private global::System.Int32 _BuyerID;
        partial void OnBuyerIDChanging(global::System.Int32 value);
        partial void OnBuyerIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Order_Buyer", "Buyer")]
        public Buyer Buyer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Buyer>("TextileMangementSystemModel.FK_Order_Buyer", "Buyer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Buyer>("TextileMangementSystemModel.FK_Order_Buyer", "Buyer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Buyer> BuyerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Buyer>("TextileMangementSystemModel.FK_Order_Buyer", "Buyer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Buyer>("TextileMangementSystemModel.FK_Order_Buyer", "Buyer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Demand_Order", "Demand")]
        public EntityCollection<Demand> Demands
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Demand>("TextileMangementSystemModel.FK_Demand_Order", "Demand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Demand>("TextileMangementSystemModel.FK_Demand_Order", "Demand", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Meeting_Order", "Meeting")]
        public Meeting Meeting
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meeting>("TextileMangementSystemModel.FK_Meeting_Order", "Meeting").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meeting>("TextileMangementSystemModel.FK_Meeting_Order", "Meeting").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Meeting> MeetingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meeting>("TextileMangementSystemModel.FK_Meeting_Order", "Meeting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Meeting>("TextileMangementSystemModel.FK_Meeting_Order", "Meeting", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextileMangementSystemModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextileMangementSystemModel", Name="Yarn")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Yarn : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Yarn object.
        /// </summary>
        /// <param name="demandNo">Initial value of the DemandNo property.</param>
        /// <param name="m_C_Dia">Initial value of the M_C_Dia property.</param>
        /// <param name="f_Gsum">Initial value of the F_Gsum property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="test">Initial value of the Test property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Yarn CreateYarn(global::System.Int32 demandNo, global::System.Int32 m_C_Dia, global::System.Int32 f_Gsum, global::System.Double quantity, global::System.String type, global::System.String test, global::System.DateTime date)
        {
            Yarn yarn = new Yarn();
            yarn.DemandNo = demandNo;
            yarn.M_C_Dia = m_C_Dia;
            yarn.F_Gsum = f_Gsum;
            yarn.Quantity = quantity;
            yarn.Type = type;
            yarn.Test = test;
            yarn.Date = date;
            return yarn;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DemandNo
        {
            get
            {
                return _DemandNo;
            }
            set
            {
                if (_DemandNo != value)
                {
                    OnDemandNoChanging(value);
                    ReportPropertyChanging("DemandNo");
                    _DemandNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DemandNo");
                    OnDemandNoChanged();
                }
            }
        }
        private global::System.Int32 _DemandNo;
        partial void OnDemandNoChanging(global::System.Int32 value);
        partial void OnDemandNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 M_C_Dia
        {
            get
            {
                return _M_C_Dia;
            }
            set
            {
                OnM_C_DiaChanging(value);
                ReportPropertyChanging("M_C_Dia");
                _M_C_Dia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("M_C_Dia");
                OnM_C_DiaChanged();
            }
        }
        private global::System.Int32 _M_C_Dia;
        partial void OnM_C_DiaChanging(global::System.Int32 value);
        partial void OnM_C_DiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 F_Gsum
        {
            get
            {
                return _F_Gsum;
            }
            set
            {
                OnF_GsumChanging(value);
                ReportPropertyChanging("F_Gsum");
                _F_Gsum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F_Gsum");
                OnF_GsumChanged();
            }
        }
        private global::System.Int32 _F_Gsum;
        partial void OnF_GsumChanging(global::System.Int32 value);
        partial void OnF_GsumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Double _Quantity;
        partial void OnQuantityChanging(global::System.Double value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Test
        {
            get
            {
                return _Test;
            }
            set
            {
                OnTestChanging(value);
                ReportPropertyChanging("Test");
                _Test = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Test");
                OnTestChanged();
            }
        }
        private global::System.String _Test;
        partial void OnTestChanging(global::System.String value);
        partial void OnTestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextileMangementSystemModel", "FK_Yarn_Demand", "Demand")]
        public Demand Demand
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Demand>("TextileMangementSystemModel.FK_Yarn_Demand", "Demand").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Demand>("TextileMangementSystemModel.FK_Yarn_Demand", "Demand").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Demand> DemandReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Demand>("TextileMangementSystemModel.FK_Yarn_Demand", "Demand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Demand>("TextileMangementSystemModel.FK_Yarn_Demand", "Demand", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
